# Generated by Django 4.2 on 2023-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_child_human_icecream_icecreammarket_spare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='quantity',
            field=models.SmallIntegerField(blank=True, verbose_name='Количество шариков'),
        ),
    ]
